name: Build and deploy Next.js app to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.PUBLISH_PROFILE }}
  WEBAPP_NAME: "GraphLM"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          
      - name: npm install, build, and test
        run: |
          npm install --legacy-peer-deps
          npm run build
          
      - name: Prepare deployment package
        run: |
          # Check what was actually built
          ls -la .next/
          # Copy the Next.js standalone build if it exists
          if [ -d ".next/standalone" ]; then
            cp -r .next/standalone ./deploy
            cp -r .next/static ./deploy/.next/
            cp -r public ./deploy/
          else
            # Fallback: use the entire .next directory
            mkdir -p ./deploy
            cp -r .next ./deploy/
            cp -r public ./deploy/
            cp package.json ./deploy/
          fi
          
      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: "production"
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package: ./deploy



